export const dynamicQuestions = [
  "When was SwiftCash Financial Solutions founded?",
  "Where is the headquarters of SwiftCash Financial Solutions located?",
  "Who are the founders of SwiftCash Financial Solutions?",
  "What is the mission of SwiftCash Financial Solutions?",
  "What is Jiokolee Loan?",
  "Who are the target customers for Jiokolee Loan?",
  "What are the features of Jiokolee Loan?",
  "What is the application process for Jiokolee Loan?",
  "How is repayment done for Jiokolee Loan?",
  "What credit scoring methods are used for Jiokolee Loan?",
  "How quickly can funds be disbursed for Jiokolee Loan after approval?",
  "What documents are required to apply for Jiokolee Loan?",
  "Can a new loan be applied for if there is an existing one?",
  "What happens if a repayment is not made on time for Jiokolee Loan?",
  "How is the interest calculated for Jiokolee Loan?",
  "Is there a credit check for Jiokolee Loan?",
  "Can the loan limit be increased for Jiokolee Loan?",
  "How can the loan status be checked for Jiokolee Loan?",
  "Is it possible to repay the loan early for Jiokolee Loan?",
  "What should be done if an application for Jiokolee Loan is rejected?",
  "What is Biashara Boost?",
  "Who are the target customers for Biashara Boost?",
  "What are the features of Biashara Boost?",
  "What is the application process for Biashara Boost?",
  "How is repayment done for Biashara Boost?",
  "What risk assessment methods are used for Biashara Boost?",
  "Can the loan from Biashara Boost be used for any business purpose?",
  "Does Biashara Boost offer grace periods?",
  "What collateral is accepted for secured loans in Biashara Boost?",
  "How long does the approval process take for Biashara Boost?",
  "Can a business less than 6 months old apply for Biashara Boost?",
  "What is the difference between a term loan and a line of credit in Biashara Boost?",
  "How often are repayments made for Biashara Boost?",
  "Can the loan be restructured if a business faces difficulties in Biashara Boost?",
  "Are there any prepayment penalties for Biashara Boost?",
  "What business advisory services are included in Biashara Boost?",
  "What is Elimu Advance?",
  "Who are the target customers for Elimu Advance?",
  "What are the features of Elimu Advance?",
  "What is the application process for Elimu Advance?",
  "How is repayment done for Elimu Advance?",
  "What insurance is provided for Elimu Advance?",
  "Can the loan from Elimu Advance cover living expenses?",
  "What happens if educational status changes for Elimu Advance?",
  "Can one apply for Elimu Advance while studying abroad?",
  "How does the grace period work for Elimu Advance?",
  "Can the loan be repaid while still studying for Elimu Advance?",
  "What are the criteria for a guarantor for Elimu Advance?",
  "Is there an age limit for applicants of Elimu Advance?",
  "Can Elimu Advance be used for short professional courses?",
  "How does the career counseling service work for Elimu Advance?",
  "What happens if a job cannot be found after graduation for Elimu Advance?",
  "What is Akiba Smart?",
  "Who are the target customers for Akiba Smart?",
  "What are the features of Akiba Smart?",
  "How often is interest paid for Akiba Smart?",
  "Can Akiba Smart account be linked to M-Pesa?",
  "Is there a minimum balance required for Akiba Smart?",
  "How many withdrawals can be made per month for Akiba Smart?",
  "Can automatic savings transfers be set up for Akiba Smart?",
  "Is the Akiba Smart account insured?",
  "Can multiple Akiba Smart accounts be opened?",
  "How can the account balance be checked for Akiba Smart?",
  "Are there any account maintenance fees for Akiba Smart?",
  "Can the Akiba Smart account be accessed through an ATM?",
  "What is Tujenge Together?",
  "Who are the target customers for Tujenge Together?"
  ];